### ISSUE TITLE
integration test failed waiting for hive port to open

### ISSUE THREAD

**Issue by tracycarley** [beltran/gohive#125]
Hi there

I have two general questions:
1) Is that possible to refactor the code to make it work with thrift 0.10? For some reason, I will need to downgrade thrift to be 0.10 so as to pass the integration test for my other modules. We pinned down the thrift to 0.10 internally for other reasons. 
I'm still new to thrift, still learning and see how much work will be needed in this area. 
2) As I forked the repo and tried the integration test (no code change yet), it failed at the step - waiting for hive port to open. I checked that 10000 locally has been open.  I also have `kinit, klist, kdestroy1`  installed locally. hs2.example.com is an alias for 127.0.0.1 in /etc/hosts.`
```
+ counter=19
+ [[ 19 -gt 18 ]]
+ echo 'Waited for three minutes and hive didn'\''t appear to start'
Waited for three minutes and hive didn't appear to start
+ docker logs hs2.example
```

```
2020-11-05T22:54:14,291  INFO [NotificationEventPoll 0] metastore.RetryingMetaStoreClient: RetryingMetaStoreClient proxy=class org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient ugi=hive/hs2.example.com@EXAMPLE.COM (auth:KERBEROS) retries=1 delay=1 lifetime=0
2020-11-05T22:54:14,292  INFO [NotificationEventPoll 0] metastore.HiveMetaStore: 2: get_config_value: name=metastore.batch.retrieve.max defaultValue=50
2020-11-05T22:54:14,292  INFO [NotificationEventPoll 0] HiveMetaStore.audit: ugi=hive/hs2.example.com@EXAMPLE.COM       ip=unknown-ip-addr      cmd=get_config_value: name=metastore.batch.retrieve.max defaultValue=50
2020-11-05T22:54:21,902 ERROR [HiveServer2-Handler-Pool: Thread-66] server.TThreadPoolServer: Error occurred during processing of message.
java.lang.RuntimeException: org.apache.thrift.transport.TTransportException: Invalid status 71
        at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:219) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.hadoop.hive.metastore.security.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory$1.run(HadoopThriftAuthBridge.java:694) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.hadoop.hive.metastore.security.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory$1.run(HadoopThriftAuthBridge.java:691) ~[hive-exec-3.1.2.jar:3.1.2]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_272]
        at javax.security.auth.Subject.doAs(Subject.java:360) ~[?:1.8.0_272]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1742) ~[hadoop-common-2.7.7.jar:?]
        at org.apache.hadoop.hive.metastore.security.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory.getTransport(HadoopThriftAuthBridge.java:691) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:269) ~[hive-exec-3.1.2.jar:3.1.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: org.apache.thrift.transport.TTransportException: Invalid status 71
        at org.apache.thrift.transport.TSaslTransport.sendAndThrowMessage(TSaslTransport.java:232) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:184) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.thrift.transport.TSaslServerTransport.handleSaslStartMessage(TSaslServerTransport.java:125) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:271) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.thrift.transport.TSaslServerTransport.open(TSaslServerTransport.java:41) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:216) ~[hive-exec-3.1.2.jar:3.1.2]
        ... 10 more
2020-11-05T22:54:31,937 ERROR [HiveServer2-Handler-Pool: Thread-66] server.TThreadPoolServer: Error occurred during processing of message.
java.lang.RuntimeException: org.apache.thrift.transport.TTransportException: Invalid status 71
        at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:219) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.hadoop.hive.metastore.security.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory$1.run(HadoopThriftAuthBridge.java:694) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.hadoop.hive.metastore.security.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory$1.run(HadoopThriftAuthBridge.java:691) ~[hive-exec-3.1.2.jar:3.1.2]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_272]
        at javax.security.auth.Subject.doAs(Subject.java:360) ~[?:1.8.0_272]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1742) ~[hadoop-common-2.7.7.jar:?]
        at org.apache.hadoop.hive.metastore.security.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory.getTransport(HadoopThriftAuthBridge.java:691) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:269) ~[hive-exec-3.1.2.jar:3.1.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: org.apache.thrift.transport.TTransportException: Invalid status 71
        at org.apache.thrift.transport.TSaslTransport.sendAndThrowMessage(TSaslTransport.java:232) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:184) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.thrift.transport.TSaslServerTransport.handleSaslStartMessage(TSaslServerTransport.java:125) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:271) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.thrift.transport.TSaslServerTransport.open(TSaslServerTransport.java:41) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:216) ~[hive-exec-3.1.2.jar:3.1.2]
        ... 10 more
2020-11-05T22:54:41,966 ERROR [HiveServer2-Handler-Pool: Thread-66] server.TThreadPoolServer: Error occurred during processing of message.
java.lang.RuntimeException: org.apache.thrift.transport.TTransportException: Invalid status 71
        at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:219) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.hadoop.hive.metastore.security.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory$1.run(HadoopThriftAuthBridge.java:694) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.hadoop.hive.metastore.security.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory$1.run(HadoopThriftAuthBridge.java:691) ~[hive-exec-3.1.2.jar:3.1.2]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_272]
        at javax.security.auth.Subject.doAs(Subject.java:360) ~[?:1.8.0_272]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1742) ~[hadoop-common-2.7.7.jar:?]
        at org.apache.hadoop.hive.metastore.security.HadoopThriftAuthBridge$Server$TUGIAssumingTransportFactory.getTransport(HadoopThriftAuthBridge.java:691) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:269) ~[hive-exec-3.1.2.jar:3.1.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: org.apache.thrift.transport.TTransportException: Invalid status 71
        at org.apache.thrift.transport.TSaslTransport.sendAndThrowMessage(TSaslTransport.java:232) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:184) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.thrift.transport.TSaslServerTransport.handleSaslStartMessage(TSaslServerTransport.java:125) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:271) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.thrift.transport.TSaslServerTransport.open(TSaslServerTransport.java:41) ~[hive-exec-3.1.2.jar:3.1.2]
        at org.apache.thrift.transport.TSaslServerTransport$Factory.getTransport(TSaslServerTransport.java:216) ~[hive-exec-3.1.2.jar:3.1.2]
        ... 10 more
+ exit 1

```

**Comment by beltran** [comment]
Hello,

> For some reason, I will need to downgrade thrift to be 0.10 so as to pass the integration test for my other modules. We pinned down the thrift to 0.10 internally for other reasons. I'm still new to thrift, still learning and see how much work will be needed in this area.

This seems more like a golang dependency issue, there must be a way to reconcile this, different dependencies of the same package in dependencies you have. I don't have the context of your error, but it seems to be [a problem other people have and have solved](https://stackoverflow.com/questions/57952397/how-to-resolve-conflicting-go-module-dependencies-when-a-top-level-module-and-on)

As for the error I think that happens when connecting to hive. It seems like hive has started successfully. How do you get the error exactly? Are you running `bash ./scripts/integration.sh`? Then you need a few more steps. You need to create as well thee krb5 configuration which you can do with [this command](https://github.com/beltran/gohive/blob/master/.travis.yml#L33). Overall [these commands](https://github.com/beltran/gohive/blob/master/.travis.yml#L24-L46) run the tests in travis so by reproducing them you should be able to run the tests locally. What do you get when you run `klist`? You should get something like this:
```
root@vmi:~/gohive# klist
Ticket cache: FILE:/tmp/krb5_gohive
Default principal: hive/hs2.example.com@EXAMPLE.COM

Valid starting       Expires              Service principal
10/26/2020 12:29:44  10/27/2020 12:29:44  krbtgt/EXAMPLE.COM@EXAMPLE.COM
10/27/2020 11:09:27  10/27/2020 12:29:44  hive/hs2.example.com@EXAMPLE.COM
```

**Comment by tracycarley** [comment]
> This seems more like a golang dependency issue, there must be a way to reconcile this, different dependencies of the same package in dependencies you have. I don't have the context of your error, but it seems to be [a problem other people have and have solved](https://stackoverflow.com/questions/57952397/how-to-resolve-conflicting-go-module-dependencies-when-a-top-level-module-and-on)

Thanks for the reference. In my case, we use dep and go.toml to manage the dependencies. We use `[overwrite](https://stackoverflow.com/questions/48360951/force-a-specific-version-for-a-dependency-when-using-dep)` to pin down the thrift 0.10 to make sure the direct/transient dependency points only to 0.10. I don't think go dep will allow two overwrite on the same vendor in the go toml file. That's why I wonder how much work needed to lower the thrift and refactor the gohive code.

**Comment by beltran** [comment]
> That's why I wonder how much work needed to lower the thrift and refactor the gohive code

I don't see a reason why it wouldn't be possible, I think both versions are pretty compatible for golang, it may just work by changing the version, but that would have to be on a fork, not the main project.
