### ISSUE TITLE
LDAP authentication with HTTPS Does Not Work

### ISSUE THREAD

**Issue by tahmed-wish** [beltran/gohive#183]
We are running into an issue with connecting to Hive using LDAP + TLS.

The following snippet shows how we are utilizing the library:
```
cfg := gohive.NewConnectConfiguration()
cfg.Username = u.user
cfg.Password = u.password
cfg.Service = "hive"
cfg.Database = h.dbName
cfg.TransportMode = "http"'
cfg.TLSConfig = &tls.Config{}

connection, err := gohive.Connect(h.host, h.port, "NONE", cfg)
if err != nil {
  log.Fatalf("gohive.Connect : Error : %s\n", err)
}
```

This yields the following exception on the client side:
```
2022-04-14T15:36:03.566-0700    FATAL   pkg/log.go:143  gohive.Connect : Error : Error while executing query: TStatus({StatusCode:ERROR_STATUS InfoMessages:[*org.apache.hive.service.cli.HiveSQLException:Invalid SessionHandle: SessionHandle [463e200c-1693-430a-a3a0-3e13982353ce]:39:38 org.apache.hive.service.cli.session.SessionManager:getSession:SessionManager.java:579 org.apache.hive.service.cli.CLIService:executeStatementAsync:CLIService.java:308 org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:562 org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1557 org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1542 org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39 org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39 org.apache.thrift.server.TServlet:doPost:TServlet.java:83 org.apache.hive.service.cli.thrift.ThriftHttpServlet:doPost:ThriftHttpServlet.java:207 javax.servlet.http.HttpServlet:service:HttpServlet.java:523 javax.servlet.http.HttpServlet:service:HttpServlet.java:590 org.eclipse.jetty.servlet.ServletHolder:handle:ServletHolder.java:852 org.eclipse.jetty.servlet.ServletHandler:doHandle:ServletHandler.java:544 org.eclipse.jetty.server.handler.ScopedHandler:nextHandle:ScopedHandler.java:233 org.eclipse.jetty.server.session.SessionHandler:doHandle:SessionHandler.java:1581 org.eclipse.jetty.server.handler.ScopedHandler:nextHandle:ScopedHandler.java:233 org.eclipse.jetty.server.handler.ContextHandler:doHandle:ContextHandler.java:1307 org.eclipse.jetty.server.handler.ScopedHandler:nextScope:ScopedHandler.java:188 org.eclipse.jetty.servlet.ServletHandler:doScope:ServletHandler.java:482 org.eclipse.jetty.server.session.SessionHandler:doScope:SessionHandler.java:1549 org.eclipse.jetty.server.handler.ScopedHandler:nextScope:ScopedHandler.java:186 org.eclipse.jetty.server.handler.ContextHandler:doScope:ContextHandler.java:1204 org.eclipse.jetty.server.handler.ScopedHandler:handle:ScopedHandler.java:141 org.eclipse.jetty.server.handler.gzip.GzipHandler:handle:GzipHandler.java:772 org.eclipse.jetty.server.handler.HandlerWrapper:handle:HandlerWrapper.java:127 org.eclipse.jetty.server.Server:handle:Server.java:494 org.eclipse.jetty.server.HttpChannel:handle:HttpChannel.java:374 org.eclipse.jetty.server.HttpConnection:onFillable:HttpConnection.java:268 org.eclipse.jetty.io.AbstractConnection$ReadCallback:succeeded:AbstractConnection.java:311 org.eclipse.jetty.io.FillInterest:fillable:FillInterest.java:103 org.eclipse.jetty.io.ChannelEndPoint$2:run:ChannelEndPoint.java:117 org.eclipse.jetty.util.thread.strategy.EatWhatYouKill:runTask:EatWhatYouKill.java:336 org.eclipse.jetty.util.thread.strategy.EatWhatYouKill:doProduce:EatWhatYouKill.java:313 org.eclipse.jetty.util.thread.strategy.EatWhatYouKill:tryProduce:EatWhatYouKill.java:171 org.eclipse.jetty.util.thread.strategy.EatWhatYouKill:run:EatWhatYouKill.java:129 org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread:run:ReservedThreadExecutor.java:367 java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1149 java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:624 java.lang.Thread:run:Thread.java:750] SqlState:<nil> ErrorCode:0xc00029c0ec ErrorMessage:0xc000308180})
```

Looking at the Hive logs it yields:
```
2022-04-14T17:53:28,518  INFO [etp1337659716-50] thrift.ThriftHttpServlet: Could not validate cookie sent, will try to generate a new cookie
2022-04-14T17:53:29,017  INFO [etp1337659716-50] thrift.ThriftHttpServlet: Cookie added for clientUserName tahmed
2022-04-14T17:53:29,131  WARN [etp1337659716-50] thrift.ThriftCLIService: Error executing statement: 
org.apache.hive.service.cli.HiveSQLException: Invalid SessionHandle: SessionHandle [8fc66ab0-f620-4714-9799-2d1c5eed6345]
	at org.apache.hive.service.cli.session.SessionManager.getSession(SessionManager.java:579) ~[hive-service-3.1.2-amzn-4.jar:3.1.2-amzn-4]
	at org.apache.hive.service.cli.CLIService.executeStatementAsync(CLIService.java:308) ~[hive-service-3.1.2-amzn-4.jar:3.1.2-amzn-4]
	at org.apache.hive.service.cli.thrift.ThriftCLIService.ExecuteStatement(ThriftCLIService.java:562) ~[hive-service-3.1.2-amzn-4.jar:3.1.2-amzn-4]
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1557) ~[hive-exec-3.1.2-amzn-4.jar:3.1.2-amzn-4]
	at org.apache.hive.service.rpc.thrift.TCLIService$Processor$ExecuteStatement.getResult(TCLIService.java:1542) ~[hive-exec-3.1.2-amzn-4.jar:3.1.2-amzn-4]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) ~[hive-exec-3.1.2-amzn-4.jar:3.1.2-amzn-4]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) ~[hive-exec-3.1.2-amzn-4.jar:3.1.2-amzn-4]
	at org.apache.thrift.server.TServlet.doPost(TServlet.java:83) ~[hive-exec-3.1.2-amzn-4.jar:3.1.2-amzn-4]
	at org.apache.hive.service.cli.thrift.ThriftHttpServlet.doPost(ThriftHttpServlet.java:207) ~[hive-service-3.1.2-amzn-4.jar:3.1.2-amzn-4]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:523) ~[jakarta.servlet-api-4.0.3.jar:4.0.3]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[jakarta.servlet-api-4.0.3.jar:4.0.3]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:544) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.server.Server.handle(Server.java:494) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) ~[jetty-io-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117) ~[jetty-io-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367) ~[jetty-runner-9.4.20.v20190813.jar:9.4.20.v20190813]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_322]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_322]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
```

After a lot of time spent debugging we determined the root cause was there being no cookie jar. We tried reusing the inMemoryCookieJar but kept seeing the following error message on the client side:
```
HTTP Response code: 500
```

We eventually realized the current implementation of inMemoryCookieJar is a little strange, namely it is not propagating all cookies received from the server. Finally, after adding the following implementation of inMemoryCookieJar, it worked for async=true queries.
```
type inMemoryCookieJar struct {
	storage map[string][]*http.Cookie
}

func (jar inMemoryCookieJar) SetCookies(u *url.URL, cookies []*http.Cookie) {
	jar.storage[u.Host] = cookies
}

func (jar inMemoryCookieJar) Cookies(u *url.URL) []*http.Cookie {
	return jar.storage[u.Host]
}
```

There are still many questions that are yet to be answered:
- The above solution returns `HTTP 431` for sync queries but works perfectly for async queries. Why?
- In the current implementation of inMemoryCookieJar, why is the last cookie stored? Why aren't all cookies stored? https://github.com/beltran/gohive/blob/master/hive.go#L1228
- In the current implementation of inMemoryCookieJar, why are the cookies cleared after getting fetched? https://github.com/beltran/gohive/blob/master/hive.go#L1243

**Comment by beltran** [comment]
Hello, thank you for debugging this and providing such a detailed explanation, sorry you went through so much trouble.

> LDAP authentication with HTTPS Does Not Work #183

This is tested though, it should be working, at least in the limited test environment, but I'm not sure what's different about your setup, maybe you have more hosts? Which is perfectly valid and would point to the tests being insufficient. 

> The above solution returns HTTP 431 for sync queries but works perfectly for async queries. Why?

Async sends less queries to Hive, [this code](https://github.com/beltran/gohive/blob/af07897b1734e771f9c9fafc379ae346f0047fa1/hive.go#L520-L551) sends requests to Hive that I imagine is failing because the headers are too big (HTTP 431 error). I'm guessing returning `jar.storage[u.Host]` is making the header too big.  `MaxHeaderBytes` is set in the server so there's not much to do but reduce the size of the header. I'm guessing you shouldn't be returning all the cookies but only one of them, I'm not sure which without inspecting the cookies, maybe try to return the last cookie only but keep a per host cookie?


> In the current implementation of inMemoryCookieJar, why is the last cookie stored? Why aren't all cookies stored?
> In the current implementation of inMemoryCookieJar, why are the cookies cleared after getting fetched?

I'll be happy to merge this changes if the current tests are passing if you create a pull request. As for why it was done like this in the original implementation, I can't remember.

**Comment by tahmed-wish** [comment]
> This is tested though, it should be working, at least in the limited test environment, but I'm not sure what's different about your setup, maybe you have more hosts? Which is perfectly valid and would point to the tests being insufficient.

It works perfectly in our staging environment which has 1 host. However in production there are many hosts and that is where we are seeing the issue.

> Async sends less queries to Hive, [this code](https://github.com/beltran/gohive/blob/af07897b1734e771f9c9fafc379ae346f0047fa1/hive.go#L520-L551) sends requests to Hive that I imagine are failing because the headers are too big (HTTP 431 error). I'm guessing returning `jar.storage[u.Host]` is making the header too big. `MaxHeaderBytes` is set in the server so there's not much to do but reduce the size of the header. I'm guessing you shouldn't be returning all the cookies but only one of them, I'm not sure which without inspecting the cookies, maybe try to return the last cookie only but keep a per host cookie?

I did some investigation and these three cookies are received from server side.
- AWSALB
- AWSALBCORS
- hive.server2.auth

The issue is that the Golang HTTP client keeps appending the same cookie over and over again, which results in the Cookie header becoming way too big. See https://github.com/golang/go/blob/master/src/net/http/client.go#L171

For example this is the largest cookie header from client side.
```
hive.server2.auth=<REDACTED>; hive.server2.auth=<REDACTED>; hive.server2.auth=<REDACTED>
```

I'm having trouble implementing a Cookie Jar that fixes this issue, but I'm fairly certain it's a bug 🤔

**Comment by tahmed-wish** [comment]
This seems like an issue that can't be fixed.. it seems these guys: https://github.com/gobuffalo/buffalo/issues/631 were also having the same issue. Why did Go write their HTTP client this way? 😅

**Comment by beltran** [comment]
> The issue is that the Golang HTTP client keeps appending the same cookie over and over again, which results in the Cookie header becoming way too big. See https://github.com/golang/go/blob/master/src/net/http/client.go#L171

Wow that's unfortunate. I've found [this](https://gist.github.com/neil90/97a2e3272e24a0db8f7c3fcfe606aea8#file-hive-site-xml-L3689-L3691) very poorly documented parameter: `hive.server2.thrift.http.request.header.size`, which if you're able to set to a bigger size, may solve the problem. There are other parameters in that file that may be useful as well, like `hive.server2.thrift.http.response.header.size`, but I think it could be enough with the first one.

**Comment by tahmed-wish** [comment]
We were finally able to fix the issue.. here is the final implementation of cookie jar that worked:
```
type inMemoryCookieJar struct {
	previousStorage map[string]bool
	storage map[string][]http.Cookie
}

func (jar inMemoryCookieJar) SetCookies(u *url.URL, cookies []*http.Cookie) {
	for _, cookie := range cookies {
		// Skip setting duplicate cookies
		if jar.previousStorage[cookie.Name] {
			continue
		}

		jar.storage["cliservice"] = append(jar.storage["cliservice"], *cookie)
	}
}

func (jar inMemoryCookieJar) Cookies(u *url.URL) []*http.Cookie {
	cookiesArray := []*http.Cookie{}
	for pattern, cookies := range jar.storage {
		if strings.Contains(u.String(), pattern) {
			for i := range cookies {
				cookiesArray = append(cookiesArray, &cookies[i])
			}

			// Delete from storage
			delete(jar.storage, pattern)
		}
	}

	// Make sure never to return cookie again
	// This is to avoid HTTP 431 (Request Header Fields Too Large)
	for _, cookie := range cookiesArray {
		jar.previousStorage[cookie.Name] = true
	}

	return cookiesArray
}

func newCookieJar() inMemoryCookieJar {
	storage := make(map[string][]http.Cookie)
	previousStorage := make(map[string]bool)
	return inMemoryCookieJar{previousStorage, storage}
}
```

I initially tried only sending the cookies if the values changed, however that did not work and I kept getting HTTP 431. After sending the cookie name just once, it somehow worked. I've spent a little too long on debugging this so I'm happy with this hotfix as long as it works. Any thoughts on the solution?

**Comment by beltran** [comment]
Well, it's pretty good news that you got it working. I'm not sure I understand the code, `jar.previousStorage` grows indefinitely right? And then once a cookie it's sent it's never sent again. I guess this makes sense. I think setting `hive.server2.thrift.http.request.header.size` would've worked as well. In any case, happy that it was solved! I'll close this now then.

**Comment by beltran** [comment]
This is actually a bug in the client, would you be able to open a pull request with the fix mentioned in the [previous comment](https://github.com/beltran/gohive/issues/183#issuecomment-1104375304) :). Looks like anyone running several hosts will run into this problem

**Comment by tahmed-wish** [comment]
I'm having some trouble running integration tests, will try to do it end of this week since I have to balance full-time work.
